### ISSUE TITLE
Using a .gitignore file to hide API keys

### ISSUE THREAD

**Issue by j-a-c-k-goes** [maryojo/netflix-clone#1]
# .env Exposing API Keys

Because the API Keys are kept in .env, this file (.env) should not be visible in the repository. 

## Fix
`cd netflix-clone` 
`touch .gitignore`
`echo .env > .gitignore`
`git add .gitignore`
` git commit -m ".gitignore added"`

(re-merge from here)

**Comment by maryojo** [comment]
Though I already have a .gitignore file, the .env file was missing from it, thanks for pointing it out

**Comment by j-a-c-k-goes** [comment]
No worries, thanks for taking the time to address this!
